### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by KevinDoughty** [trusktr/geometry-interfaces#9]
I would like to implement tests but there are no test suites in the package.json file. I would choose my own and make a pull request, but I don't know if you have a preference. There is a good chance I'd pick one you don't like. Any recommendations?

**Comment by trusktr** [comment]
Done in https://github.com/trusktr/geometry-interfaces/releases/tag/v2.0.0 (the build scripts, formatting scripts, publishing scripts, and test scripts are handled by lume cli, which uses [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/) for unit tests).
